# Generated by Django 2.1.7 on 2019-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0002_auto_20190212_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
