# Generated by Django 3.0.dev20190214152302 on 2019-03-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0004_auto_20190224_2338'),
        ('housing_app', '0003_apartment_description'),
    ]

    operations = [
    ]
