# Generated by Django 2.1.7 on 2019-03-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0005_merge_20190303_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/home.jpg', upload_to=''),
        ),
    ]
