# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('furnished', models.CharField(max_length=5)),
                ('pets', models.CharField(max_length=5)),
            ],
        ),
    ]
