# Generated by Django 2.1.7 on 2019-03-04 20:58

from django.db import migrations, models
import django.db.models.deletion
import housing_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0006_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='No Review')),
                ('score', models.IntegerField(default=0)),
                ('username', models.CharField(default='noUser', max_length=100)),
                ('apartmentID', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/blank_profile.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='ratings',
            field=models.ForeignKey(default=housing_app.models.Rating(), on_delete=django.db.models.deletion.CASCADE, to='housing_app.Rating'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ratings',
            field=models.ForeignKey(default=housing_app.models.Rating, on_delete=django.db.models.deletion.CASCADE, to='housing_app.Rating'),
        ),
    ]
