# Generated by Django 2.1.7 on 2019-03-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0007_auto_20190304_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='apartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='housing_app.Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='housing_app.Profile'),
            preserve_default=False,
        ),
    ]
