# Generated by Django 2.1.7 on 2019-03-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0007_auto_20190324_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/blank_profile.png', upload_to=''),
        ),
    ]
