# Generated by Django 2.1.7 on 2019-03-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0008_auto_20190330_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='compare0',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='compare1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compare0',
            field=models.ForeignKey(blank=True, default='NULL', on_delete='SET_NULL', related_name='compare0', to='housing_app.Apartment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compare1',
            field=models.ForeignKey(blank=True, default='NULL', on_delete='SET_NULL', related_name='compare1', to='housing_app.Apartment'),
        ),
    ]
