# Generated by Django 2.1.7 on 2019-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0008_auto_20190327_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='static/images/blank_profile.png', max_length=255, upload_to=''),
        ),
    ]
