# Generated by Django 2.1.7 on 2019-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0008_auto_20190327_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='compare',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compare0',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_DEFAULT', related_name='compare0', to='housing_app.Apartment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compare1',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_DEFAULT', related_name='compare1', to='housing_app.Apartment'),
        ),
    ]
