# Generated by Django 2.1.7 on 2019-03-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0009_auto_20190330_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='compare0',
            field=models.ForeignKey(blank=True, default=0, on_delete='SET_NULL', related_name='compare0', to='housing_app.Apartment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='compare1',
            field=models.ForeignKey(blank=True, default=0, on_delete='SET_NULL', related_name='compare1', to='housing_app.Apartment'),
        ),
    ]
