# Generated by Django 2.1.7 on 2019-04-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0009_apartment_image'),
        ('housing_app', '0010_auto_20190404_0243'),
    ]

    operations = [
    ]
