# Generated by Django 2.1.7 on 2019-04-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0011_merge_20190404_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/blank_profile.png', max_length=255, upload_to=''),
        ),
    ]
