# Generated by Django 2.1.7 on 2019-04-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0012_auto_20190409_2012'),
        ('housing_app', '0009_auto_20190410_0752'),
    ]

    operations = [
    ]
