# Generated by Django 2.1.7 on 2019-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0013_auto_20190413_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=150)),
                ('apartment_name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('bedrooms', models.CharField(max_length=100)),
                ('bathrooms', models.CharField(default='--', max_length=100)),
            ],
        ),
    ]
