# Generated by Django 2.1.7 on 2019-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0014_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='maxBR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='maxPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='minBR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='minPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/blank_profile.png', max_length=255, upload_to='images/'),
        ),
    ]
